"""empty message

Revision ID: 188ce5bc43a8
Revises: 103c1e64bb2f
Create Date: 2024-09-06 12:47:35.018485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188ce5bc43a8'
down_revision = '103c1e64bb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedor')
    # ### end Alembic commands ###
