"""empty message

Revision ID: e607650fc5ee
Revises: e5941f21babd
Create Date: 2024-10-07 16:44:27.241960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e607650fc5ee'
down_revision = 'e5941f21babd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('anuncio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['anuncio_id'], ['anuncio.id'], name='transaction_anuncio_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='transaction_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey'),
    sa.UniqueConstraint('transaction_id', name='transaction_transaction_id_key')
    )
    # ### end Alembic commands ###
